### ISSUE TITLE
pretrained model gives error

### ISSUE THREAD

**Issue by azmiara** [kang205/DVBPR#2]
`--2019-05-28 12:31:19--  (try: 2)  http://cseweb.ucsd.edu/~wckang/DVBPR/DVBPR_auc_100_39728.ckpt.data-00000-of-00001
Connecting to cseweb.ucsd.edu (cseweb.ucsd.edu)|132.239.8.30|:80... failed: Connection timed out.
Retrying.`

This is the message when I try to run the pretrained model as it fails to connect to the link.

**Comment by kang205** [comment]
Google Drive link: https://drive.google.com/drive/folders/1ShTSqCrlEL0r2-261BIeMZUeTDmeN2H5?usp=sharing
