### ISSUE TITLE
Cannot execute file (Main.py) in DVBPR gives  KeyError: 'productid'

### ISSUE THREAD

**Issue by ayush9198gupta** [kang205/DVBPR#4]
Hello,

I am using your model for outfits recommmendation , while running the Main.py in folder DVBPR revert back with the code error 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 205, in load_image_async
    (uuu,iii,jjj)=sample(user_train)
  File "main.py", line 194, in sample
    i = user[u][random.randrange(numu)]['productid']
KeyError: 'productid'
```

I have made following changes in file:-

import queue
from io import StringIO
dataset = np.load('../'+dataset_name , encoding='bytes', allow_pickle=True)

Kindly suggest 
Thanks

**Comment by meghrajpardesi** [comment]
I was working on same, as the code is mainly written in Python 2, and i was using it with python 3.
try replacing
`i = user[u][random.randrange(numu)]['productid']`
with
`i = user[u][random.randrange(numu)][b'productid']`
it works for me.

**Comment by ayush9198gupta** [comment]
Thanks @meghrajpardesi  its works for me as well

**Comment by ayush9198gupta** [comment]
thanks

**Comment by ayush9198gupta** [comment]
;
