### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by SantiagoEG** [kang205/DVBPR#7]
Hi,

I am Santiago Egea a PostDoc research at Universitat of Barcelona. I am currently working on a project related to Fashion recommendation. I have been reading all the work you and your collages have been performing in this research field.
I sincerely appreciate your efforts to make your research publicly available to support other researchers. 
As part of my tasks, I am trying to reproduce the results reported in your manuscript; however, I am finding some obstacles in the evaluation part. 

Regarding the performance metric employed, AUC is used as metric to compare your proposal to state-of-the-art techniques in your manuscript. If I am properly understanding this metric, it consists on comparing embedding generated by item that the user showed interest (let´s call it embInterest) and items randomly selected (embRandom). If **|embInterest| > |embRandom|**, we consider that the recommender is generating a better recommendation that randomness and a counter is increased. The final reported metric is the mean of this counter. Am I interpreting well this validation approach?

I sincerely appreciate your time,

Best

**Comment by kang205** [comment]
Yes I think you're right. This is probably the most intuitive way to intrepret AUC, and we will have 0.5 of AUC for random guess.
